application: hellowillmcfadden
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: html/index.html
  upload: html/index.html

- url: /js
  static_dir: js
  
- url: /im
  static_dir: im
  
- url: /css
  static_dir: css
  
- url: /
  static_dir: html
  